# Generated by Django 4.2.6 on 2023-10-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_customer_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="main.order",
            ),
        ),
    ]
