# Generated by Django 4.2.6 on 2023-11-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_orderitems_price_orderitems_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
