# Generated by Django 4.2.6 on 2023-11-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_order_order_status_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(null=True),
        ),
    ]
