# Generated by Django 4.2.6 on 2023-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_orderitems_usd_price_product_usd_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="usd_price",
        ),
        migrations.AddField(
            model_name="product",
            name="euro_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
