# Generated by Django 4.2.6 on 2023-11-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_orderitems_usd_price_product_euro_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='euro_price',
            new_name='eur_price',
        ),
    ]
