# Generated by Django 4.2.6 on 2023-11-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wish List'},
        ),
    ]
