# Generated by Django 4.2.6 on 2023-11-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_alter_customeraddress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_img",
            field=models.ImageField(null=True, upload_to="customer_imgs/"),
        ),
    ]
